[theme]
base = "light"
primaryColor = "#176b68"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#edf2f7"
textColor = "#20334b"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true

